remove secu

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -8,55 +8,8 @@ env:
 
 jobs:
   build:
-    name: Build and Test
+    name: Build and Package
     runs-on: ubuntu-22.04
-    permissions:
-      contents: read
-      security-events: write
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
-      - name: Set up JDK
-        uses: actions/setup-java@v4
-        with:
-          distribution: temurin
-          java-version: 17
-          cache: gradle
-      - name: Build, unit tests and integration tests
-        run: |
-          chmod +x gradlew
-          ./gradlew build
-      - name: Code vulnerability scanning
-        uses: anchore/scan-action@v3
-        id: scan
-        with:
-          path: "${{ github.workspace }}"
-          fail-build: false
-          severity-cutoff: high
-      - name: Upload vulnerability report
-        uses: github/codeql-action/upload-sarif@v3
-        if: success() || failure()
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
-      - name: Setup tools
-        uses: alexellis/setup-arkade@v3
-      - name: Install tools
-        uses: alexellis/arkade-get@master
-        with:
-          kustomize: latest
-          kubeconform: latest
-      - name: Validate Kubernetes manifests
-        run: |
-          kustomize build k8s | kubeconform --strict -
-  package:
-    name: Package and Publish
-    if: ${{ github.ref == 'refs/heads/main' }}
-    needs: [ build ]
-    runs-on: ubuntu-22.04
-    permissions:
-      contents: read
-      packages: write
-      security-events: write
     steps:
       - name: Checkout source code
         uses: actions/checkout@v4
@@ -71,18 +24,47 @@ jobs:
           chmod +x gradlew
           ./gradlew bootBuildImage \
             --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-      - name: OCI image vulnerability scanning
-        uses: anchore/scan-action@v3
-        id: scan
-        with:
-          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
-          fail-build: false
-          severity-cutoff: high
-      - name: Upload vulnerability report
-        uses: github/codeql-action/upload-sarif@v3
-        if: success() || failure()
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
+
+      # - name: Build, unit tests and integration tests
+      #   run: |
+      #     chmod +x gradlew
+      #     ./gradlew build
+
+      # - name: Code vulnerability scanning
+      #   uses: anchore/scan-action@v3
+      #   id: scan
+      #   with:
+      #     path: "${{ github.workspace }}"
+      #     fail-build: false
+      #     severity-cutoff: high
+
+      # - name: Upload vulnerability report
+      #   uses: github/codeql-action/upload-sarif@v3
+      #   if: success() || failure()
+      #   with:
+      #     sarif_file: ${{ steps.scan.outputs.sarif }}
+
+      # - name: Setup tools
+      #   uses: alexellis/setup-arkade@v3
+
+      # - name: Install tools
+      #   uses: alexellis/arkade-get@master
+      #   with:
+      #     kustomize: latest
+      #     kubeconform: latest
+
+      # - name: Validate Kubernetes manifests
+      #   run: |
+      #     kustomize build k8s | kubeconform --strict -
+
+  package:
+    name: Publish
+    if: ${{ github.ref == 'refs/heads/main' }}
+    needs: [ build ]
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v4
       - name: Log into container registry
         uses: docker/login-action@v3
         with:
@@ -91,3 +73,17 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
       - name: Publish container image
         run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+
+      # - name: OCI image vulnerability scanning
+      #   uses: anchore/scan-action@v3
+      #   id: scan
+      #   with:
+      #     image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+      #     fail-build: false
+      #     severity-cutoff: high
+
+      # - name: Upload vulnerability report
+      #   uses: github/codeql-action/upload-sarif@v3
+      #   if: success() || failure()
+      #   with:
+      #     sarif_file: ${{ steps.scan.outputs.sarif }}
